spring.application.name=ai-loan-underwriting
server.port=8082

# Global switch to activate the Google GenAI Embedding Bean
spring.ai.google.genai.api-key=${GEMINI_API_KEY}

# Chat Configuration
spring.ai.google.genai.chat.model=gemini-3.5-flash

spring.config.import=optional:file:.env[.properties]